### ISSUE TITLE
Crashes whenever i try to get in my world.

### ISSUE THREAD

**Issue by JokeCoke** [Ckathode/archimedes-ships#24]
I don't know what I did to cause this.
All i did is I assembled the ship and drove a little bit
Here's the crash report:
https://drive.google.com/file/d/0BxG2cjOBYrcLZ3lMTXloNk0zMHc/view?usp=sharing

**Comment by Ckathode** [comment]
Seems like a crash that has something to do with the KoadMasters Pirates
mod. Please check out with them.

2015-08-10 20:24 GMT+02:00 JokeCoke <notifications@github.com>:

**Comment by JokeCoke** [comment]
Thanks!
